Page contributeurs côté admin
nygmasx/SchoolIndex pull request #26
Opened 2024-03-22 09:51 UTC by PeruchoRafael

Pagination, crud et affichage

2024-03-28 16:18 UTC, nygmasx requested changes

2024-03-28 16:18 UTC, nygmasx commented on src/Controller/UserController.php
> +public function editUser(Request $request, EntityManagerInterface $manager, UserPasswordHasherInterface $passwordHasher, User $user): Response
```suggestion
public function edit(User $user): Response
```
Appelez les classes du constructeur

2024-03-28 16:18 UTC, nygmasx commented on src/DataFixtures/UserFixtures.php
> +        $this->passwordHasher = $passwordHasher;
```suggestion
```

2024-03-28 16:18 UTC, nygmasx commented on src/DataFixtures/UserFixtures.php
> +    public function __construct(UserPasswordHasherInterface $passwordHasher)
```suggestion
    public function __construct(private readonly UserPasswordHasherInterface $passwordHasher)
```

2024-03-28 16:18 UTC, nygmasx commented on src/Entity/User.php
A voir pour mettre un enum

2024-03-28 16:18 UTC, nygmasx commented on src/Entity/User.php
>      {
```suggestion
    {
    
```

2024-03-28 16:18 UTC, nygmasx commented on src/Form/UserType.php
> +                ],
```suggestion
                'choices' => [
                    'Utilisateur' => 'ROLE_USER',
                    'Administrateur' => 'ROLE_ADMIN',
                ],
```
A changer (ROLE_TEACHER, ROLE_STUDENT)

2024-03-28 16:18 UTC, nygmasx commented on src/Form/UserType.php
> +}
```suggestion
}

```

2024-03-28 16:18 UTC, nygmasx commented on templates/admin/index.html.twig
>  {% endblock %}
```suggestion
{% endblock %}

```

2024-03-28 16:18 UTC, nygmasx commented on templates/admin/index.html.twig
> +</script>
```suggestion
```
A mettre dans un fichier js

2024-03-28 16:18 UTC, nygmasx commented on templates/components/datatable.html.twig
> +
```suggestion

```

2024-03-28 16:18 UTC, nygmasx commented on templates/components/pagination/custom_pagination.html.twig
> +{# tailwindcss Sliding pagination control implementation #}
```suggestion
```
Pas de commentaire stp

2024-03-28 16:18 UTC, nygmasx commented on templates/components/pagination/custom_pagination.html.twig
> +{% endif %}
```suggestion
{% endif %}

```

2024-03-28 16:18 UTC, nygmasx commented on templates/user/index.html.twig
> +{% endblock %}
```suggestion
{% endblock %}

```

2024-03-31 13:41 UTC, BouderBaden reviewed
propre brozer

2024-04-09 20:37 UTC, nygmasx approved these changes

2024-04-09 20:38 UTC, merged